name: backbone
description: Lightweight, ECS-like package for Flame and Flutter
version: 0.0.1
homepage: https://github.com/sturdykeep/backbone
documentation: https://github.com/sturdykeep/backbone/docs/docs.md
environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  flame: ^1.4.0
  flame_test: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null